services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pareta22/node-express-compose-jenkins:latest
    container_name: node-express-compose-jenkins
    ports:
      - "3001:3000"
    restart: unless-stopped
